LOGGING_LEVEL: "INFO"
LOGGING_FORMAT: "%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s"

KAFKA_BROKER: "localhost:9093"
RAW_EVENTS_TOPIC: "raw-events"

API_KEY: "1234qwerasdfzxcv"
